version: "3"
 
services:
  php:
    build:
      context: ./php
    container_name: php
    volumes:
      - ..:/app:cached
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf:cached
    working_dir: /app
    depends_on:
      - db
  nginx:
    build:
      context: ./nginx
    container_name: server
    ports:
      - "8081:80"
    volumes:
      - ..:/app:cached
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf:cached
    depends_on:
      - php
  db:
    build:
      context: ./mysql
    restart: always
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    entrypoint:
      sh -c "
        echo 'CREATE DATABASE IF NOT EXISTS webike; CREATE DATABASE IF NOT EXISTS webike_testing;' > /docker-entrypoint-initdb.d/init.sql;
        /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    ports:
      - "3306:3306"